<x-platform-layout title="Editar barbería · BarberHub" active-page="barbershops">
    <div class="mx-auto max-w-6xl space-y-6">
        <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div><h1 class="text-3xl font-bold tracking-[-0.035em] text-white sm:text-4xl">Editar barbería</h1><p class="mt-2 text-sm leading-6 text-slate-400">Actualiza los datos operativos de {{ $barbershop->name }} dentro de la plataforma.</p></div>
            <a href="{{ route('platform.barbershops.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 transition hover:text-amber-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300"><svg class="h-4 w-4" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" d="m11 5-5 5 5 5m-5-5h9"/></svg>Volver a barberías</a>
        </header>

        <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
            <section class="rounded-xl border border-slate-800 bg-[#11171d]">
                <form method="POST" action="{{ route('platform.barbershops.update', $barbershop) }}" class="space-y-6 p-5 sm:p-7">
                    @csrf
                    @method('PUT')
                    <div><h2 class="text-lg font-bold text-white">Información de la barbería</h2><p class="mt-1 text-sm text-slate-400">El slug identifica la barbería en las rutas y debe mantenerse único.</p></div>
                    <div class="grid gap-5 sm:grid-cols-2">
                        <div class="sm:col-span-2"><label for="name" class="block text-sm font-semibold text-slate-100">Nombre</label><input id="name" name="name" type="text" value="{{ old('name', $barbershop->name) }}" required autofocus autocomplete="organization" class="mt-2 block w-full rounded-lg border border-slate-700 bg-[#0b1015] px-4 py-3 text-sm text-white placeholder:text-slate-500 outline-none transition focus:border-amber-300 focus:ring-2 focus:ring-amber-300/20" placeholder="Barbería Central" /><x-input-error class="mt-2 text-amber-200" :messages="$errors->get('name')" /></div>
                        <div><label for="slug" class="block text-sm font-semibold text-slate-100">Slug</label><input id="slug" name="slug" type="text" value="{{ old('slug', $barbershop->slug) }}" required class="mt-2 block w-full rounded-lg border border-slate-700 bg-[#0b1015] px-4 py-3 text-sm text-white placeholder:text-slate-500 outline-none transition focus:border-amber-300 focus:ring-2 focus:ring-amber-300/20" placeholder="barberia-central" /><p class="mt-2 text-xs leading-5 text-slate-500">Minúsculas, números y guiones; debe ser único.</p><x-input-error class="mt-2 text-amber-200" :messages="$errors->get('slug')" /></div>
                        <div><label for="timezone" class="block text-sm font-semibold text-slate-100">Zona horaria</label><input id="timezone" name="timezone" type="text" value="{{ old('timezone', $barbershop->timezone) }}" required class="mt-2 block w-full rounded-lg border border-slate-700 bg-[#0b1015] px-4 py-3 text-sm text-white placeholder:text-slate-500 outline-none transition focus:border-amber-300 focus:ring-2 focus:ring-amber-300/20" placeholder="America/Bogota" /><x-input-error class="mt-2 text-amber-200" :messages="$errors->get('timezone')" /></div>
                        <div><label for="status" class="block text-sm font-semibold text-slate-100">Estado</label><select id="status" name="status" class="mt-2 block w-full rounded-lg border border-slate-700 bg-[#0b1015] px-4 py-3 text-sm text-white outline-none transition focus:border-amber-300 focus:ring-2 focus:ring-amber-300/20"><option value="active" @selected(old('status', $barbershop->status) === 'active')>Activa</option><option value="inactive" @selected(old('status', $barbershop->status) === 'inactive')>Inactiva</option></select><x-input-error class="mt-2 text-amber-200" :messages="$errors->get('status')" /></div>
                    </div>
                    <div class="flex flex-col-reverse gap-3 border-t border-slate-800 pt-6 sm:flex-row sm:items-center sm:justify-end"><a href="{{ route('platform.barbershops.index') }}" class="rounded-lg px-4 py-3 text-center text-sm font-semibold text-slate-300 transition hover:bg-slate-800 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-300">Cancelar</a><button type="submit" class="inline-flex items-center justify-center gap-2 rounded-lg bg-amber-300 px-5 py-3 text-sm font-bold text-[#1a1409] shadow-[0_10px_24px_rgba(251,191,36,0.13)] transition hover:bg-amber-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-100 focus-visible:ring-offset-2 focus-visible:ring-offset-[#11171d]"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="m5 12 4 4L19 6"/></svg>Guardar cambios</button></div>
                </form>
            </section>

            <aside class="h-fit rounded-xl border border-slate-800 bg-[#11171d] p-5 sm:p-6"><svg class="h-7 w-7 text-amber-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M4 21V9l8-5 8 5v12M2 21h20M8 21v-5h8v5"/></svg><h2 class="mt-4 text-lg font-bold text-white">Registro existente</h2><p class="mt-2 text-sm leading-6 text-slate-400">Edita solo datos de identificación, zona horaria y estado. Las membresías se mantienen sin cambios.</p><div class="mt-6 rounded-lg bg-[#0c1116] p-4"><p class="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Resumen</p><ul class="mt-3 space-y-3 text-sm text-slate-300"><li class="flex gap-2"><span class="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-300"></span>Slug actual: {{ $barbershop->slug }}</li><li class="flex gap-2"><span class="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-300"></span>Creada el {{ $barbershop->created_at->format('d/m/Y') }}</li><li class="flex gap-2"><span class="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-300"></span>Estado actual: {{ $barbershop->status === \App\Models\Barbershop::STATUS_ACTIVE ? 'Activa' : 'Inactiva' }}</li></ul></div></aside>
        </div>
    </div>
</x-platform-layout>
